
LUA_GLUE_BEGIN(FVector)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FRotator)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FVector2D)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FVector4)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FQuat)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FColor)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FHitResult)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FTransform)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FGuid)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FTwoVectors)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FPlane)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FIntPoint)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FIntVector)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FBox)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FBox2D)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FBoxSphereBounds)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FOrientedBox)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FMatrix)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FInputChord)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FKey)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FVector_NetQuantize)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FVector_NetQuantizeNormal)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FSoftObjectPath)
LUA_GLUE_END()

LUA_GLUE_BEGIN(FMargin)
LUA_GLUE_CTOR((float,float,float,float), 0,0,0,0)
LUA_GLUE_END()